echo '<!DOCTYPE html>'
echo '<html>'
echo '<head>'
echo '	<meta charset="utf-8">'
echo '	<meta name="description" content="Página web del hotel canino GUAU">'
echo '	<link rel="icon" href="img/logo.png" type="image/jpg" sizes=100px>'
echo '	<link rel="stylesheet" href="css/style6.css" type="text/css">'
echo '	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=yes">'
echo '	<title>Reservas - GUAU Hotel Canino</title>'

echo '</head>'
echo '<body>'
echo '<!--Comienza header-->'
echo '	<div class="header">'
echo '		<div class="content-header">'
echo        '<div class="logo">'
				
			
echo '				<h1><div class="name1">GUAU</div><a href="index.html"><img class="logo-header" src="img/logo3-2.png" width="17%" height="100%"></a><div class="name2">HOTEL CANINO</div></h1>'
echo '			</div>'

echo '			<div class="social">'
echo '				<a title="Ir a Facebook" href="https://www.facebook.com"><img class="fb" src="img/facebook_solo3.png" width="18%" height="10%" alt="Logo de Facebook"></a>'
echo '				<a title="Ir a Instagram" href="https://www.instagram.com"><img class="ig" src="img/instagram_solo.png" width="18%" height="10%" alt="Logo de Instagram"></a>'
echo '				<a title="Ir a Twitter" href="https://www.twitter.com"><img class="tw" src="img/twitter_solo.png" width="18%" height="10%" alt="Logo de Twitter"></a>'
echo '				<a title="Ir a Youtube" href="https://www.youtube.com"><img class="yt" src="img/youtube_solo.png" width="18%" height="10%" alt="Logo de YouTube"></a>'
echo '			</div>'
echo '		</div>'
echo '	</div>'
echo '	<div class="menu">'
echo '		<div class="content-menu">	'
echo '			<table class="tabla">'
echo '				<td class="opt"><a class="button" href="index.html">Inicio</a></td>'
echo '				<td class="opt"><a class="button" href="about.html">El Hotel</a></td>'
echo '				<td class="opt"><a class="button" href="rooms.html">Habitaciones</a></td>'
echo '				<td class="opt"><a class="button" href="services.html">Servicios</a></td>'
echo '				<td class="opt"><a class="button" href="booking.html">Reservas</a></td>'
echo '				<td class="opt"><a class="button" href="move.html">Traslados</a></td>'
echo '				<td class="opt"><a class="button" href="contact.html">Contacto</a></td>'
			echo '</table>'
			echo '<table class="tabla2">'
				echo '<td class="opt1"><a class="button" href="index.html">Inicio</a></td>'
				echo '<td class="opt2"><a class="button" href="about.html">El Hotel</a></td>'
				echo '<td class="opt3"><a class="button" href="rooms.html">Habitaciones</a></td>'
				echo '<td class="opt4"><a class="button" href="services.html">Servicios</a></td>'
				echo '<td class="opt5"><a class="button" href="booking.html">Reservas</a></td>'
				echo '<td class="opt6"><a class="button" href="move.html">Traslados</a></td>'
				echo '<td class="opt7"><a class="button" href="contact.html">Contacto</a></td>'
echo '			</table>'

echo '		</div>'
echo '	</div>'
	<!--Termina header-->
	<!--Comienza contenido de la pagina-->

echo '	<div class="presentacion">'
echo '		<h3 class="hotel"><b><i>Reservas</i></b></h3>'
echo '	</div>'
echo '	<p class="info-reservas"><i>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</i></p>'
echo '	<table class="booking" cellspacing="0">'
echo '		<tr>'
echo '			<td class="inter-booking" width="30"><i><b>ID</b></i></div></td>'
echo '			<td class="inter-booking" width="180"><i><b>Tipo de Habitación</a></b></i></div></td>'
echo '			<td class="inter-booking" width="200"><i><b>Nombre</a></b></i></div></td>'
echo '			<td class="inter-booking" width="70"><i><b>Cantidad de mascotas</a></b></i></div></td>'
echo '			<td class="inter-booking" width="120"><i><b>Día de la reserva</a></b></i></div></td>'
echo '		</tr>'
echo '		<tr>'
echo '			<td class="inter-booking">1</td>'
echo '			<td class="inter-booking">Room</td>'
echo '			<td class="inter-booking">Name</td>'
echo '			<td class="inter-booking">x</td>'
echo '			<td class="inter-booking">xxxx-xx-xx</td>'
echo '		</tr>'
echo '		<tr>'
echo '			<td class="inter-booking">2</td>'
echo '			<td class="inter-booking">Room</td>'
echo '			<td class="inter-booking">Name</td>'
echo '			<td class="inter-booking">x</td>'
echo '			<td class="inter-booking">xxxx-xx-xx</td>'
echo '		</tr>'
echo '		<tr>'
echo '			<td class="inter-booking">3</td>'
echo '			<td class="inter-booking">Room</td>'
echo '			<td class="inter-booking">Name</td>'
echo '			<td class="inter-booking">x</td>'
echo '			<td class="inter-booking">xxxx-xx-xx</td>'
echo '		</tr>'
echo '		<tr>'
echo '			<td class="inter-booking">4</td>'
echo '			<td class="inter-booking">Room</td>'
echo '			<td class="inter-booking">Name</td>'
echo '			<td class="inter-booking">x</td>'
echo '			<td class="inter-booking">xxxx-xx-xx</td>'
echo '		</tr>'
echo '		<tr>'
echo '			<td class="inter-booking">5</td>'
echo '			<td class="inter-booking">Room</td>'
echo '			<td class="inter-booking">Name</td>'
echo '			<td class="inter-booking">x</td>'
echo '			<td class="inter-booking">xxxx-xx-xx</td>'
echo '		</tr>'
echo '		<tr>'
echo '			<form action="send.html" action="action.php" method="post">'
echo '			<td class="inter-booking">-</td>'
echo '			<td class="inter-booking">'
echo '				<textarea class="add" name="name" rows="1" cols="34" input type="text" id="name" placeholder="Add new"></textarea>'
echo '			</td>'
echo '			<td class="inter-booking">'
echo '	        	<textarea class="add" name="surname" rows="1" cols="34" input type="text" id="surname" placeholder="Add new"></textarea>'
echo '	        </td>'
echo '			<td class="inter-booking">'
echo '	        	<textarea class="add" name="surname" rows="1" cols="34" input type="text" id="surname" placeholder="Add new"></textarea>'
echo '	        </td>'
echo '			<td class="inter-booking">'
echo '	        	<textarea class="add" name="surname" rows="1" cols="34" input type="text" id="surname" placeholder="Add new"></textarea>'
echo '	        </td>'
echo '		</tr>'
echo '		<tr>'
echo '			<td></td>'
echo '			<td></td>'
echo '			<td></td>'
echo '			<td></td>'
echo '			<td><input class="submit" type="submit" value="Agregar"></td>'
echo '		</tr>'
echo '	</form>'
echo '	</table>'
echo '	<p class="info-reservas"><i>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</i></p>'
echo '	<!--Termina contenido de la pagina-->'
echo '	<!--Comienza footer-->'
echo '	<div class="footer">'
echo '		<div class="content-footer">	'
echo '			<table class="tabla-footer">'
echo '				<td><a class="button opt1-footer" href="about.html">El Hotel</a></td>'
echo '				<td><a class="button opt2-footer" href="rooms.html">Habitaciones</a></td>'
echo '				<td><a class="button opt3-footer" href="booking.html">Reservas</a></td>'
echo '				<td><a class="button opt4-footer" href="contact.html">Contacto</a></td>'
echo '			</table>'
echo '				<p class="footer-info1">Calle 8 y Anastasio Sierra, Barrio La Falda (Piriápolis)<br>'
echo '				Teléfonos: (+598) 2288-66-99 | (+598) 096-956-589</p>'
echo '				<p class="footer-info2">Reservas: <a class="footer-mail" href="https://www.gmail.com">hotelcaninoguauinfo@gmail.com</a></p>'
echo '				<p class="footer-info3">© 2020. Hotel Canino GUAU - Todos los derechos reservados.</p>'
			
echo '		</div>'
echo '	</div>'
<!--Termina footer-->

echo '</body>'
echo '</html>'